"""perbaikan pada model peminjaman, penambahan property nama_member

Revision ID: 11d518354316
Revises: 8bb6692a47e8
Create Date: 2026-10-08 13:18:34.424979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d518354316'
down_revision: Union[str, Sequence[str], None] = '8bb6692a47e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
