"""Perbaikan pada Hpeminjaman model

Revision ID: 1ec4224fdbf0
Revises: 84c8ebcb5041
Create Date: 2026-10-04 14:44:22.432281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ec4224fdbf0'
down_revision: Union[str, Sequence[str], None] = '84c8ebcb5041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
