"""Update table user dibagian created_at dan modified_at

Revision ID: 29016c40d45b
Revises: c05b40cd6e81
Create Date: 2026-09-28 18:43:27.751440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29016c40d45b'
down_revision: Union[str, Sequence[str], None] = 'c05b40cd6e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
