"""Perbaikan pada models roles dibagian back_populates

Revision ID: 33b2190e619a
Revises: fd3a8ecd539c
Create Date: 2026-09-30 23:10:50.133370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b2190e619a'
down_revision: Union[str, Sequence[str], None] = 'fd3a8ecd539c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
