"""membuat table buku dan migrasi

Revision ID: 589c5dd68919
Revises: 2af46f58f3f7
Create Date: 2026-09-28 16:56:49.302287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589c5dd68919'
down_revision: Union[str, Sequence[str], None] = '2af46f58f3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('penulis', sa.String(length=255), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=30), nullable=False),
    sa.Column('tersedia', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('modify_at', sa.DateTime(), nullable=True),
    sa.Column('modify_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buku_id'), 'buku', ['id'], unique=False)
    op.create_index(op.f('ix_buku_judul'), 'buku', ['judul'], unique=True)
    op.create_index(op.f('ix_buku_penulis'), 'buku', ['penulis'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buku_penulis'), table_name='buku')
    op.drop_index(op.f('ix_buku_judul'), table_name='buku')
    op.drop_index(op.f('ix_buku_id'), table_name='buku')
    op.drop_table('buku')
    # ### end Alembic commands ###
