"""Perbaikan pada model dan schema Detail peminjaman, penambahan qty pada detail

Revision ID: 5e25cff34f95
Revises: b3d90c00b0ee
Create Date: 2026-10-06 13:49:56.414476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e25cff34f95'
down_revision: Union[str, Sequence[str], None] = 'b3d90c00b0ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dpeminjaman', sa.Column('qty', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dpeminjaman', 'qty')
    # ### end Alembic commands ###
