"""normalisasi model role dari user pindah ke models/roles

Revision ID: 8125a67f6223
Revises: bc3f8e7ede01
Create Date: 2026-09-29 15:00:53.736271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8125a67f6223'
down_revision: Union[str, Sequence[str], None] = 'bc3f8e7ede01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
