"""Perbaikan panjang string pada kolom no_pinjam 7 jadi 14

Revision ID: 84c8ebcb5041
Revises: cf62b0ed2fe8
Create Date: 2026-10-04 13:47:01.269502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c8ebcb5041'
down_revision: Union[str, Sequence[str], None] = 'cf62b0ed2fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hpeminjaman', 'no_pinjam',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hpeminjaman', 'no_pinjam',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    # ### end Alembic commands ###
