"""perbaikan pada model member dan peminjaman

Revision ID: 8bb6692a47e8
Revises: 8984e2b26375
Create Date: 2026-10-07 00:35:57.229063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb6692a47e8'
down_revision: Union[str, Sequence[str], None] = '8984e2b26375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
