"""perbaikan pada models peminjaman, tambah timestamp created at dan by, modify at dan by

Revision ID: 99e297cd3037
Revises: dc89c9d3a604
Create Date: 2026-10-03 17:59:56.427474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e297cd3037'
down_revision: Union[str, Sequence[str], None] = 'dc89c9d3a604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dpeminjaman', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('dpeminjaman', sa.Column('created_by', sa.String(length=50), nullable=False))
    op.add_column('dpeminjaman', sa.Column('modify_at', sa.DateTime(), nullable=True))
    op.add_column('dpeminjaman', sa.Column('modify_by', sa.String(length=50), nullable=True))
    op.add_column('hpeminjaman', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('hpeminjaman', sa.Column('created_by', sa.String(length=50), nullable=False))
    op.add_column('hpeminjaman', sa.Column('modify_at', sa.DateTime(), nullable=True))
    op.add_column('hpeminjaman', sa.Column('modify_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hpeminjaman', 'modify_by')
    op.drop_column('hpeminjaman', 'modify_at')
    op.drop_column('hpeminjaman', 'created_by')
    op.drop_column('hpeminjaman', 'created_at')
    op.drop_column('dpeminjaman', 'modify_by')
    op.drop_column('dpeminjaman', 'modify_at')
    op.drop_column('dpeminjaman', 'created_by')
    op.drop_column('dpeminjaman', 'created_at')
    # ### end Alembic commands ###
