"""perbaikan pada models dan migrasi ulang member ke database

Revision ID: aa5deed8dbf0
Revises: acdb3b722df7
Create Date: 2026-10-02 18:18:16.223717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5deed8dbf0'
down_revision: Union[str, Sequence[str], None] = 'acdb3b722df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('no_telp', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('modify_at', sa.DateTime(), nullable=True),
    sa.Column('modify_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_telp')
    )
    op.create_index(op.f('ix_member_id'), 'member', ['id'], unique=False)
    op.create_index(op.f('ix_member_nama'), 'member', ['nama'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_nama'), table_name='member')
    op.drop_index(op.f('ix_member_id'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
