"""perbaikan pada models peminjaman

Revision ID: b3d90c00b0ee
Revises: e67d7d643698
Create Date: 2026-10-05 17:23:47.877335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3d90c00b0ee'
down_revision: Union[str, Sequence[str], None] = 'e67d7d643698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hpeminjaman', 'status',
               existing_type=postgresql.ENUM('TERBUAT', 'KEMBALI', 'BATAL', name='statuspinjam'),
               type_=sa.Enum('TERBUAT', 'KEMBALI', 'DIPINJAM', 'BATAL', name='statuspinjam', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hpeminjaman', 'status',
               existing_type=sa.Enum('TERBUAT', 'KEMBALI', 'DIPINJAM', 'BATAL', name='statuspinjam', native_enum=False),
               type_=postgresql.ENUM('TERBUAT', 'KEMBALI', 'BATAL', name='statuspinjam'),
               existing_nullable=False)
    # ### end Alembic commands ###
