"""perbaikan datetime pada buku table dibagian created_at dan modify_at

Revision ID: c05b40cd6e81
Revises: e2e4ee3b93a4
Create Date: 2026-09-28 18:42:04.400984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05b40cd6e81'
down_revision: Union[str, Sequence[str], None] = 'e2e4ee3b93a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
