"""perbaikan pada table member, tambah kolom status

Revision ID: c4eb3d039797
Revises: aa5deed8dbf0
Create Date: 2026-10-02 21:18:09.180928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4eb3d039797'
down_revision: Union[str, Sequence[str], None] = 'aa5deed8dbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('status', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'status')
    # ### end Alembic commands ###
