"""Perbaikan relasi role pada user

Revision ID: ca9376c6ee24
Revises: e1cdd76860db
Create Date: 2026-09-30 23:06:08.751600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9376c6ee24'
down_revision: Union[str, Sequence[str], None] = 'e1cdd76860db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
