"""perbaikan pada kolom table peminjaman, member, dan buku

Revision ID: cf62b0ed2fe8
Revises: 99e297cd3037
Create Date: 2026-10-03 18:01:31.547299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf62b0ed2fe8'
down_revision: Union[str, Sequence[str], None] = '99e297cd3037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
