"""Membuat model Hpeminjaman, Dpeminjaman dan migrasi ke database

Revision ID: dc89c9d3a604
Revises: eca149d4dc9f
Create Date: 2026-10-03 17:52:47.351211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc89c9d3a604'
down_revision: Union[str, Sequence[str], None] = 'eca149d4dc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
