"""perbaikan pada table user, hapus kolom role, redundance terkait relation table

Revision ID: e1cdd76860db
Revises: 8125a67f6223
Create Date: 2026-09-29 20:04:00.762665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1cdd76860db'
down_revision: Union[str, Sequence[str], None] = '8125a67f6223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
