"""Tambah kolom qty pada table buku

Revision ID: e2e4ee3b93a4
Revises: 589c5dd68919
Create Date: 2026-09-28 16:58:12.092772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e4ee3b93a4'
down_revision: Union[str, Sequence[str], None] = '589c5dd68919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buku', sa.Column('qty', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buku', 'qty')
    # ### end Alembic commands ###
