"""Tambah kolom status pada models peminjaman

Revision ID: e67d7d643698
Revises: 1ec4224fdbf0
Create Date: 2026-10-05 15:01:25.411404

"""
from models.peminjaman import StatusPinjam
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67d7d643698'
down_revision: Union[str, Sequence[str], None] = '1ec4224fdbf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    status_enum = sa.Enum(StatusPinjam, name='statuspinjam')
    status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('hpeminjaman', sa.Column('status', status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hpeminjaman', 'status')
    # ### end Alembic commands ###
