"""Membuat model Hpeminjaman, Dpeminjaman dan migrasi ke database

Revision ID: eca149d4dc9f
Revises: c4eb3d039797
Create Date: 2026-10-03 17:51:30.862208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca149d4dc9f'
down_revision: Union[str, Sequence[str], None] = 'c4eb3d039797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hpeminjaman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_pinjam', sa.String(length=7), nullable=False),
    sa.Column('qty_pinjam', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_pinjam', sa.DateTime(), nullable=False, server_defaults=sa.text('now()')),
    sa.Column('tanggal_kembali', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hpeminjaman_id'), 'hpeminjaman', ['id'], unique=False)
    op.create_index(op.f('ix_hpeminjaman_no_pinjam'), 'hpeminjaman', ['no_pinjam'], unique=True)
    op.create_table('dpeminjaman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('buku_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buku_id'], ['buku.id'], ),
    sa.ForeignKeyConstraint(['header_id'], ['hpeminjaman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpeminjaman_id'), 'dpeminjaman', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dpeminjaman_id'), table_name='dpeminjaman')
    op.drop_table('dpeminjaman')
    op.drop_index(op.f('ix_hpeminjaman_no_pinjam'), table_name='hpeminjaman')
    op.drop_index(op.f('ix_hpeminjaman_id'), table_name='hpeminjaman')
    op.drop_table('hpeminjaman')
    # ### end Alembic commands ###
