"""Perbaikan v2 pada roles_ref menjadi role_ref di models user

Revision ID: fd3a8ecd539c
Revises: ca9376c6ee24
Create Date: 2026-09-30 23:08:33.025508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3a8ecd539c'
down_revision: Union[str, Sequence[str], None] = 'ca9376c6ee24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
